[project]
name = "dl-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cupy-cuda13x>=14.0.1",
    "ipywidgets>=8.1.8",
    "matplotlib>=3.10.8",
    "nltk>=3.9.4",
    "numpy>=2.4.2",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.1",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "torch>=2.10.0",
    "torch-summary>=1.4.5",
    "torchattack>=1.7.2",
    "torchtext>=0.18.0",
    "torchvision>=0.25.0",
    "tqdm>=4.67.3",
    "ucimlrepo>=0.0.7",
    "wordcloud>=1.9.6",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
